# frozen_string_literal: true
source "https://rubygems.org"
ruby '>= 2.3.0'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'erubis'
gem 'rack'
gem 'rake'
gem 'minitest'
gem 'minitest-reporters'

group :production do
  gem 'passenger'
  gem 'puma'
end

group :development do
  gem 'pry'
  gem 'rubocop'
end
